### ISSUE TITLE
Webservices plugin

### ISSUE THREAD

**Issue by b-keller** [shinken-monitoring/mod-glpi-helpdesk#1]
I can't find your version of Webservices plugin for GLPI on : 
https://github.com/IPM-France/glpi_plugin_webservices

I already use  the original webservice plugin in GLPI. So, can I install your version also for a general usage ? or the two versions can coexist...

Thanks

**Comment by mohierf** [comment]
_Sorry for late answering ..._

My version is here : https://github.com/mohierf/glpi_webservices/tree/glpi0.84

You cannot install the original version and mine on the same configuration ... but my version is fuly compatible with the original one.

**Comment by b-keller** [comment]
Hi,
So, I install your webservice plugin : no problem...

the Glpi Helpdesk module is load correctly: 
INFO: [Shinken] Correctly loaded glpi-helpdesk as an old-new-style shinken module :|

I use default conf, glpi and shinken on the same host.
but no new tab in the element view... how to debug this ?

thanks

**Comment by mohierf** [comment]
You should have something like this in the `brokerd.log`: 

```
[1441434907] INFO: [broker-master] Correctly loaded glpi-helpdesk as an old-new-style shinken module :|
[1441434908] INFO: [broker-master] Correctly loaded glpi-helpdesk as an old-new-style shinken module :|
[1441434908] INFO: [broker-master] [glpi-helpdesk] Get a Glpi helpdesk module for plugin glpi-helpdesk
[1441434908] INFO: [broker-master] [glpi-helpdesk] Glpi Web Service host:login: http://glpi085/glpi/plugins/webservices/xmlrpc.php:shinken
[1441434908] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441434908] INFO: [broker-master] [glpi-helpdesk] Connecting to http://glpi085/glpi/plugins/webservices/xmlrpc.php
[1441434908] INFO: [broker-master] [glpi-helpdesk] Connection opened
[1441434908] INFO: [broker-master] [glpi-helpdesk] Authentication in progress...
[1441434908] INFO: [broker-master] [glpi-helpdesk] Authenticated, session : ol7le2ssrskk7p1n7i1fj4dhc5
[1441434908] INFO: [broker-master] [glpi-helpdesk] helpdesk configuration: {'templates': [{'impact': '5', 'content': "Bourrage papier dans l'imprimante", 'name': 'Bourrage imprimante', 'slas_id': '1', 'template_type': 'incident', 'status': '1', 'itilcategories_id': '2', 'type': '1', 'id': '3', 'urgency': '4'}, {'template_type': 'incident', 'status': '1', 'slas_id': '1', 'id': '2', 'name': u'Probl\xe8me de communication'}], 'session': 'ol7le2ssrskk7p1n7i1fj4dhc5', 'categories': [{'completename': 'Bourrage imprimante', 'comment': '', 'entity_id': '0', 'name': 'Bourrage imprimante', 'entity_name': 'Root entity', 'is_request': '0', 'parent_id': '0', 'is_incident': '1', 'id_template_incident': '3', 'id': '2', 'id_template_request': '0'}, {'completename': 'Communication borne', 'comment': '', 'entity_id': '0', 'name': 'Communication borne', 'entity_name': 'Root entity', 'is_request': '0', 'parent_id': '0', 'is_incident': '1', 'id_template_incident': '2', 'id': '1', 'id_template_request': '0'}], 'types': ['incident', 'request']}
[1441434908] INFO: [broker-master] I correctly loaded the modules: [glpi-helpdesk,ui-graphite,auth-ws-glpi]
[1441434908] INFO: [broker-master] [WebUI] Module found: glpi-helpdesk
[1441434909] INFO: [broker-master] [WebUI] loaded plugin helpdesk
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for pi2
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for graphite
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for wheezy
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for pi1
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : kiosk-0001 is {'entities_id': '6', 'items_id': '9', 'hostsid': '3', 'itemtype': 'Computer'}
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_BP_host
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_Root
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_dubaiairport1
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_desk1
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_desk2
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0001 is {'entities_id': '3', 'items_id': '13', 'hostsid': '4', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0002 is {'entities_id': '3', 'items_id': '14', 'hostsid': '5', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0003 is {'entities_id': '3', 'items_id': '15', 'hostsid': '7', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0004 is {'entities_id': '3', 'items_id': '16', 'hostsid': '8', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0005 is {'entities_id': '3', 'items_id': '17', 'hostsid': '9', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0006 is {'entities_id': '3', 'items_id': '18', 'hostsid': '10', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0007 is {'entities_id': '3', 'items_id': '19', 'hostsid': '11', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0008 is {'entities_id': '3', 'items_id': '20', 'hostsid': '12', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0009 is {'entities_id': '3', 'items_id': '21', 'hostsid': '13', 'itemtype': 'Computer'}
[1441434910] INFO: [broker-master] [glpi-helpdesk] initial host status : sim-0010 is {'entities_id': '3', 'items_id': '22', 'hostsid': '14', 'itemtype': 'Computer'}
[1441434910] WARNING: [broker-master] [glpi-helpdesk] no custom _HOSTID and/or _ITEMTYPE and/or _ITEMSID and/or _ENTITIESID for _fake_ipm
```

1/ The module dumps its parameters and then connects on the Glpi web service interface to authenticate
2/ The module gets the Glpi Tickets configuration 
3/ The module waits for Shinken hosts initial states

Once made this configuration you should have a Ticket tab in the host element view where to display the tickets known for the host

**PS:** sorry we I did not yet finished fully testing and documenting this module ...

**Comment by b-keller** [comment]
this is the broker.log : 

```
[1441481310] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441481311] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441481312] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441481313] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441481314] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1441481314] INFO: [broker-master] [glpi-helpdesk] Connecting to http://localhost/glpi/plugins/webservices/xmlrpc.php
[1441481314] INFO: [broker-master] [glpi-helpdesk] Connection opened
[1441481314] INFO: [broker-master] [glpi-helpdesk] Authentication in progress...
[1441481314] ERROR: [broker-master] [glpi-helpdesk] Authentication refused, fault code: 1 (AccÃƒÂ¨s refusÃƒÂ©)
[1441481314] ERROR: [broker-master] The instance glpi-helpdesk raised an exception , I remove it!
[1441481314] ERROR: [broker-master] Back trace of this remove: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Shinken-2.4-py2.7.egg/shinken/modulesmanager.py", line 200, in try_instance_init
    inst.init()
  File "/var/lib/shinken/modules/glpi-helpdesk/module.py", line 95, in init
    raise GlpiTicketsError
GlpiTicketsError
```

glpi-helpdesk.cfg : 

```
## Module:      glpi-helpdesk
## Loaded by:   WebUI

# GLPI needs Webservices plugin to be installed and enabled.
define module {
    module_name     glpi-helpdesk
    module_type     glpi-helpdesk

    # Glpi Web service URI
    uri             http://localhost/glpi/plugins/webservices/xmlrpc.php
        # Default : shinken
    login_name      shinken
    # Default : shinken
    login_password  shinken
}
```

config web service GLPI : 

![webservice1](https://cloud.githubusercontent.com/assets/12746104/9700950/176133de-5417-11e5-82b8-ef61bd786604.PNG)

I don't understand why the connexion is refuse...

**Comment by b-keller** [comment]
Hi,

after modified /var/lib/shinken/modules/glpi-helpdesk/module.py  
`self.uri = getattr(modconf, 'uri', 'http://localhost/glpi/plugins/webservices/xmlrpc.php')`
with the ip address of the glpi server (which is the same as shinken, but...)
`self.uri = getattr(modconf, 'uri', 'http://192.168.XXX.XXX/glpi/plugins/webservices/xmlrpc.php')`

the connection is ok but there is an other error : 

```
[1442568012] INFO: [broker-master] [glpi-helpdesk] Authentication in progress...
[1442568012] INFO: [broker-master] [glpi-helpdesk] Authenticated, session : 4ktuggo0ioj5epi1i29p9q45e4
[1442568012] ERROR: [broker-master] [glpi-helpdesk] Authentication refused, fault code: 2 (Unknown method (kiosks.getHelpdeskConfiguration))
[1442568012] ERROR: [broker-master] The instance glpi-helpdesk raised an exception , I remove it!
[1442568012] ERROR: [broker-master] Back trace of this remove: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/Shinken-2.4-py2.7.egg/shinken/modulesmanager.py", line 200, in try_instance_init
    inst.init()
  File "/var/lib/shinken/modules/glpi-helpdesk/module.py", line 96, in init
    raise GlpiTicketsError
GlpiTicketsError
```

Do you have infos about "kiosks.getHelpdeskConfiguration" ?

**Comment by mohierf** [comment]
Why did you modified source code to change a configuration parameter that is stored in the module cfg file ? It is not necessary ... simply change the parameter in the `glpi-helpdesk.cfg` file!

I must have a new look inside this module because I am not yet sure it will work on another configuration than mine :/P I will try to have a look in the next few days ...

**Comment by b-keller** [comment]
Ok, thanks.

**Comment by rbe1733** [comment]
Hi,

I try to use shinken module "glpi-helpdesk" with glpi 0.90.4.
Shinken and GLPI are installed on 2 different servers.

I installed on GLPI the plugin webservices v1.6.0 because the version available on https://github.com/mohierf/glpi_webservices is not compatible with version 0.90.4.

I have an authentification problem on shinken side : [glpi-helpdesk] Authentication refused, fault code: 1 (brokerd.log)
I made some tests and i'm pretty sure that the IP range and login/password are not the cause.
I guess a kind of incompatibility with this version of GLPI.

I don't know if my configuration may work or if i do have to revert to GPLI v0.85.

Thanks for your help

Kind Regards

Richard

**Comment by mohierf** [comment]
I never tested this experimental feature with the most recent Glpi version ... and, currently, I do not have any means to test on Glpi 0.90. As soon as I have I will make a test ... in the mean time, if you can activate the debug logs, I will perharps be able to help ?

**Comment by rbe1733** [comment]
Hi Frédéric,

Many thanks for your very reactive support.

I ran extra tests which i hope will be useful to investigate deeper the problem.
Tell me if you need any other informations.

Kind Regards

Richard

1) Test with authentication ==> RESULT : Authentication refused, fault code: 1 (Accès refusé) and NO TRACE IN GLPI WEB SERVICES HISTORY

-- Shiken side (pegasus server and brokerd in DEBUG mode) --
root@pegasus:/var/log/shinken# cat /etc/shinken/modules/glpi-helpdesk.cfg

## Module:      glpi-helpdesk

## Loaded by:   WebUI

# GLPI needs Webservices plugin to be installed and enabled.

define module {
    module_name     glpi-helpdesk
    module_type     helpdesk

```
# Glpi Web service URI
uri             http://draconis.stargate.net/glpi/plugins/webservices/xmlrpc.php
# Default : shinken
login_name      shinken
# Default : shinken
login_password  shinken

# Web service source
# Default source is shinken
source          Shinken
```

}

-- GLPI side (draconis server)
![image](https://cloud.githubusercontent.com/assets/18539270/17128508/729740cc-530d-11e6-8cb4-2323073c5c0d.png)

-- brokerd.log --
[1469515229] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1469515229] DEBUG: [broker-master] [elastic-logs] service check result received: pegasus/Cpu
[1469515229] INFO: [broker-master] [glpi-helpdesk] Connecting to http://draconis.stargate.net/glpi/plugins/webservices/xmlrpc.php
[1469515229] DEBUG: [broker-master] [elastic-logs] time to manage 2 broks (1.0114s)
[1469515229] DEBUG: [broker-master] [Graphite] Data sent to Carbon:
pegasus.Cpu.cpu_prct_used 3.75 1469515228

[1469515229] DEBUG: [broker-master] [elastic-logs] queue length: 0
[1469515229] INFO: [broker-master] [glpi-helpdesk] Connection opened
[1469515229] INFO: [broker-master] [glpi-helpdesk] Authentication in progress...
[1469515229] DEBUG: [broker-master] [mongo-logs] service check result received: pegasus/Cpu
[1469515229] DEBUG: [broker-master] Time to send 2 broks (0 secs)
[1469515229] DEBUG: [broker-master] [mongo-logs] time to manage 2 broks (1.0130s)
[1469515229] DEBUG: [broker-master] [mongo-logs] queue length: 0
[1469515229] ERROR: [broker-master] [glpi-helpdesk] Authentication refused, fault code: 1 (Accès refusé)
[1469515229] ERROR: [broker-master] The instance glpi-helpdesk raised an exception , I remove it!
[1469515229] ERROR: [broker-master] Back trace of this remove: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shinken/modulesmanager.py", line 200, in try_instance_init
    inst.init()
  File "/var/lib/shinken/modules/glpi-helpdesk/module.py", line 91, in init
    raise GlpiTicketsError
GlpiTicketsError

2) Test without authentication ==> RESULT : Authentication refused, fault code: 12 (Login failed (Identifiant ou mot de passe erroné)) BUT TRACE IN GLPI WEB SERVICES HISTORY

-- Shinken side --

## Module:      glpi-helpdesk

## Loaded by:   WebUI

# GLPI needs Webservices plugin to be installed and enabled.

define module {
    module_name     glpi-helpdesk
    module_type     helpdesk

```
# Glpi Web service URI
uri             http://draconis.stargate.net/glpi/plugins/webservices/xmlrpc.php
# Default : shinken
#login_name      shinken
# Default : shinken
#login_password  shinken

# Web service source
# Default source is shinken
source          Shinken
```

}

-- GLPI side --
![image](https://cloud.githubusercontent.com/assets/18539270/17128623/62ea2260-530e-11e6-8ea0-2caf6eafe338.png)

-- brokerd.log --
[1469516031] INFO: [broker-master] Trying to init module: glpi-helpdesk
[1469516031] DEBUG: [broker-master] [mongo-logs] time to manage 1 broks (1.0103s)
[1469516031] DEBUG: [broker-master] Time to send 1 broks (0 secs)
[1469516031] INFO: [broker-master] [glpi-helpdesk] Connecting to http://draconis.stargate.net/glpi/plugins/webservices/xmlrpc.php
[1469516031] DEBUG: [broker-master] [elastic-logs] time to manage 1 broks (1.0088s)
[1469516031] DEBUG: [broker-master] [mongo-logs] queue length: 0
[1469516031] INFO: [broker-master] [glpi-helpdesk] Connection opened
[1469516031] DEBUG: [broker-master] [elastic-logs] queue length: 0
[1469516031] INFO: [broker-master] [glpi-helpdesk] Authentication in progress...
[1469516031] ERROR: [broker-master] [glpi-helpdesk] Authentication refused, fault code: 12 (Login failed (Identifiant ou mot de passe erroné))
[1469516031] ERROR: [broker-master] The instance glpi-helpdesk raised an exception , I remove it!
[1469516031] ERROR: [broker-master] Back trace of this remove: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/shinken/modulesmanager.py", line 200, in try_instance_init
    inst.init()
  File "/var/lib/shinken/modules/glpi-helpdesk/module.py", line 91, in init
    raise GlpiTicketsError
GlpiTicketsError

-- GLPI History --
![image](https://cloud.githubusercontent.com/assets/18539270/17128785/7e740bf8-530f-11e6-8ac3-9c17e62a5231.png)
